export { default as Recommend } from './recommend'
export { default as Singer }    from './singer'
export { default as Rank }   from './rank'
export { default as Search } from './user'
export { default as Player } from './player'
export { default as Playlist } from './playlist'
